# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - task --list

  hello:
    aliases: [h]
    desc: Print a greeting message
    cmds:
      - echo "Hello, World!"
